# Generated by Django 3.1.6 on 2021-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pukich',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='susi',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product image'),
        ),
    ]
