# Generated by Django 3.1.6 on 2021-02-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='susi',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
